suyashkumar/dicom

- element/dataset.go
- element/element.go
- parse.go
- write/writer_test.go
This change refactors the API used to extract integer values from a DICOM `Element`. A top level API `GetInt` and `GetInts` retrieve the stored integer-like value (which may be `uint16`, `int8`, etc) consistently as either an `int64` or `[]int64`.
If the caller wants to access the "true" value of the integer(s), the caller can do so by directly accessing `Element.Value` and type casting as needed based on the Element's `VR`. 
All legacy methods to retrieve specific types of ints have been removed. 
There is some small-in-practice efficiency trade off to be typecasting these integers, but this API is clearer and easier to use and cleans up the code a fair bit. Power users can still easily work with the `Value`s directly if efficiency is of the utmost importance. 
This chance also factors …
> Refactor Element integer API

- element.go
- read.go
This change introduces an initial implementation of readElement and readSequence. It also adds a new `Value` type for `Elements` called `ElementsPtrsValue` which is a slice of pointers to other (sub)Elements that may be part of an Element instance (e.g. if there's a sequence).
> Add initial readElement, readSequence, and ElementPtrsValue

- cmd/dicomtest/main.go
- element.go
- mocks/pkg/dicomio/mock_reader.go
- parse.go
- pkg/dicomio/reader.go
- read.go
This change implements the initial `dicomio.Reader`, which unblocks the first end-to-end test of the rewritten prototype parser. A simple test program was added to test the library, which appears to successfully parse several simple test DICOMs!
Several bugs were also caught and fixed. 
More robust e2e testing against a suite of public DICOMs should be added, in addition to more comprehensive unit testing as this rewritten library begins to take shape. 
Since this is on the rewrite branch, going to submit this to continue moving forward and building out a prototype rewrite.
> Implement dicomio.Reader, add simple test program, fix some bugs

- element.go
- parse.go
- read.go
This change implements correct parsing of sequence elements. More details on the structure of nested items can be found at the [standard here](http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_7.5.html).
Previously, the complete SQ items were read, but not parsed correctly into sequence items. 
This change also added support for additional integer VR parsing.
> [Rewritten Prototype] Implement SQ Item parsing

- parse.go
There are 2 potential fixes in the PR. The first (as commit 'Simplest Fix') is to leave `NewParserFromFile` mostly the same and add close the file before returning from the function with an error. The second fix (as 'Issue #66 better fix', which is named incorrectly and should be issue #75) is to utilize the helper function `NewParserFromBytes` to allow the function `NewParserFromFile` to open and close the relevant file within the function and not have to worry about managing open files later.
> Explicitly close file on error in NewParserFromFile

- write/writer.go
`make` output:
```
make
go mod download
/Library/Developer/CommandLineTools/usr/bin/make test
go test ./...
ok  	github.com/suyashkumar/dicom	0.389s
?   	github.com/suyashkumar/dicom/cmd/dicomutil	[no test files]
?   	github.com/suyashkumar/dicom/constants	[no test files]
ok  	github.com/suyashkumar/dicom/dicomio	(cached)
?   	github.com/suyashkumar/dicom/dicomlog	[no test files]
ok  	github.com/suyashkumar/dicom/dicomtag	(cached)
ok  	github.com/suyashkumar/dicom/dicomuid	(cached)
?   	github.com/suyashkumar/dicom/element	[no test files]
?   	github.com/suyashkumar/dicom/frame	[no test files]
ok  	github.com/suyashkumar/dicom/query	0.018s
ok  	github.com/suyashkumar/dicom/write	(cached)
go build -o build/dicomutil ./cmd/dicomutil
```
On the DICOM file where I experience issue 80, reading …
> write: pad certain VRs with spaces instead of null bytes

- parse.go
This fixes #77 and appears to work on provided DICOMs. This is a relatively quick fix, that does seem to get the job done. There are some minor improvements that can be made in future PRs, but it will be best to get these changes in to unblock future work. 
This also appears to fix #82, and fix #65 (we are able to parse those images without errors).
For most of the provided images, the issue was that an icon image sequence could appear in the DICOMs in addition to the primary PixelData. When reading that particular image sequence, a different set of metadata tags need to be used (instead of the global ones, which apply only to the core PixelData).
There may be additional work to fully and correctly parsing icon image sets (most of the icons seem to be unpopulated in the sample images), …
> Support parsing NativePixelData when it appears multiple times in a DICOM

- cmd/dicomtest/main.go
- dataset.go
- element.go
- mocks/pkg/dicomio/mock_reader.go
- parse.go
- pkg/dicomio/reader.go
- read.go
This implements native pixel data parsing on the rewrite branch. This includes fixes done on the mainline branch to parse PixelData properly if it appears multiple times in a DICOM (PR #79). This also includes some fixes to better handle value multiplicity.
> [Rewrite] Native Pixel Data Parsing, handle value multiplicity.

- element.go
- go.mod
- go.sum
- mocks/pkg/dicomio/mock_reader.go
- parse.go
- pkg/charset/charset.go
- pkg/dicomio/reader.go
- transfer_syntax.go
This PR brings the rewritten 1.0 branch into parity with the existing code on master regarding character set support. It seems like character sets may need to be scoped to Sequences (see #88), which will be looked into shortly. More extensive testing will come in a follow up PR.
> [Rewrite] Port over support for character sets

- dataset.go
- dataset_test.go
This change implements a simple FlatIterator for a dataset which sends all elements in a Dataset to a channel, including elements nested inside Sequences. This also implements initial sanity tests and testable examples, along with a helper `FindElementByTagNested` function.
> Implement initial FlatIterator for a Dataset

- cmd/dicomutil/main.go
- dataset.go
- element.go
- element_test.go
- parse.go
- read.go
🎉 This implements initial JSON Marshal support for `Dataset` and `Element`. This also adds in a `--json` option to `dicomutil` to print a JSON representation of the parsed dataset to stdout. 
Probably there will be a __lot more cleanup and finetuning to do__ (e.g. better serialization of tag), but this is a start. Of course, it would also be good to implement unmarshal support in the future too. 
This addresses #13, but is on the rewrite branch (not main yet).
Here's what a random element looks like JSON serialized:
```json
{
"tag": {
"Group": 2,
"Element": 0
},
"VR": 4,
"rawVR": "UL",
"valueLength": 4,
"value": [
198
]
}
```
Of course, nested elements in DICOM sequences are supported too.
> Implement initial JSON Marshal support for Dataset and Element

- cmd/dicomutil/main.go
- dataset.go
- dataset_test.go
- element.go
- element_test.go
This implements a clean string serialization for an Element and Dataset. Note JSON serialization was added in #98, so this is in addition to that.
It looks something like this:
```
[
Tag: (0054,0081)
Tag Name: NumberOfSlices
VR: VRUInt16List
VR Raw: US
VL: 2
Value: &{[111]}
]
```
When a `Dataset` is serialized to a string, children elements in a Sequence are indented, like so:
```
[
Tag: (0012,0064)
Tag Name: DeidentificationMethodCodeSequence
VR: VRSequence
VR Raw: SQ
VL: 4294967295
Value: &{[824634238848 824634239072 824634239296 824634239552 824634239776 824634240000 824634240224 824634240448]}
]
[
Tag: (0008,0100)
Tag Name: CodeValue
VR: VRStringList
VR Raw: SH
VL: 6
Value: &{[%!d(string=113100)]}
]
[
Tag: (0008,0102)
Tag Name: CodingSchemeDesignator
VR: VRStringList
VR Raw: SH
VL: 4 …
```
> [Rewrite] Implement clean string serialization for a Dataset

- write/writer.go
Function `write.DataSetToFile` does not pass `opts` argument further down the line.  This PR fixes this.
> Add missing opts parameter to downstream call to write.Dataset

- dataset_test.go
- element.go
- element_test.go
- parse.go
- read.go
Not sure if I prefer this or just moving all the these Value implementations to a pkg, but let's try this out for now.
> Reduce API surface by making the various value implementations private

- element.go
- element_test.go
This addresses #107 by adding NewValue. We can also add a NewElement helper that calls NewValue under the hood and possibly validates VR with the underlying data. This is mostly helpful for consumers testing or a future write package imo.
> Add NewValue helper function

- parse.go
- read.go
This fixes #109 by ensuring the full byte array is read for VR=OB. 
The dicoms provided in #109 will be added to a test set in an upcoming PR around a larger integration testing framework.
> Fix VR=OB byte reads

- cmd/dicomutil/main.go
- parse.go
This updates the Parse API for the dicom package. 
For parsing the dataset at once, simply call `dicom.Parse(...)`
```go
// Parse parses the entire DICOM at the input io.Reader into a Dataset of DICOM Elements. Use this if you are
// looking to parse the DICOM all at once, instead of element-by-element.
func Parse(in io.Reader, bytesToRead int64, frameChan chan *frame.Frame) (Dataset, error)
```
```go
data, err := dicom.Parse(...)
```
If you need to parse element-by-element, simply use the `dicom.Parser`:
```go
p, err := dicom.NewParser(...) // This parses the DICOM header and metadata
element, err := p.Next() 
meta := p.GetMetadata()  // if you need it.
...
```
> Update Parser API

- parse_test.go
This adds initial basic benchmarks over `testfiles/`. 
In the future, we can add a GitHub action to use benchstat to compare benchmark diffs.
> Add benchmarks over testfiles/

- mocks/pkg/dicomio/mock_reader.go
- parse.go
- pkg/dicomio/reader.go
- read_test.go
- write.go
This change adds some support to read non-standard DICOMs that do not include the magic word at offset 128 (as described in #59). 
This change attempts to peek ahead at the magic word to see if it is there. If not, it effectively rewinds back to byte zero, skips metadata parsing, and goes back to typical parsing (with a transfer syntax default of LittleEndian Implicit). 
While some of the non-standard dicoms in #59 appear to be broken in other unrelated ways, most of them work with this fix.
> Support reading non-standard DICOMs without magic word

- element.go
- write.go
- write_test.go
This change makes several cleanups and refactors to the write package and write package tests.
* Write no longer takes a pointer to the dataset in its API (it shouldn't do this, because the caller should not have to worry about it being modified in the Write internals imo).
* Significant refactor to write tests to be table tests, and to not rely on an assertion package.
* TestWrite updated to read DICOM back from disk for verification
* Several other write package API uplifts and updates.
> write package: refactors and improvements (tests and core package)

- write.go
- write_test.go
This change allows writing of a Dataset without a TransferSyntax metadata element, so long as the DefaultMissingTransferSyntax option is provided to `Write`.
This fixes #132.
> write: implement support for missing TransferSyntax with option

- cmd/dicomutil/main.go
This changes `dicomutil` to write out native PixelData frames as PNGs, which preserves pixel values unlike encoding the raw values back out to jpeg (particularly when the raw values are small).
> cmd/dicomutil: write out native PixelData as PNGs

- dataset_test.go
- element_test.go
- pkg/dicomio/writer.go
- read.go
- write.go
- write_test.go
This change adds support and tests for writing out sequences in the write package. All sequences are written with the undefined length encoding option (http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_7.5.html). 
This change also improves other various issues and APIs in the write code.
> write: Support for writing Sequences, and other misc write package improvements.

- read.go
- write.go
- write_test.go
This addresses #143 by parsing elements with VR=AT as Ints (instead of the default fallback of parsing as strings).
> Initial support for AT Tag

- pkg/frame/native.go
- pkg/frame/native_test.go
This adds a more comprehensive test for converting NativeFrame data into an image, and also fixes the row selector in GetImage.
> Add NativeFrame GetImage conversion test, fix row selection in conversion.

- Makefile
This updates the way the `VERSION` Makefile variable works.
> Update VERSION Makefile variable

- Makefile
- read.go
- read_test.go
This change reduces the number of allocations in `readNativeFrames`. Instead of allocating a slice for each pixel's samples, a single flat buffer slice is allocated upfront of the size `pixelsPerFrame*samplesPerPixel`. Later, ranges in that slice are referred to in the larger 2D slice. This leads to there only being two calls to `make`, leading to significant performance gains.
On my machine running `make bench-diff`:
```
name           old time/op  new time/op  delta
Parse/1.dcm-8  2.29ms ± 1%  1.95ms ± 3%  -15.00%  (p=0.008 n=5+5)
Parse/2.dcm-8  2.27ms ± 1%  1.94ms ± 0%  -14.41%  (p=0.008 n=5+5)
Parse/3.dcm-8  2.10ms ± 0%  1.81ms ± 2%  -13.77%  (p=0.008 n=5+5)
Parse/4.dcm-8   240ms ± 1%   196ms ± 4%  -18.27%  (p=0.008 n=5+5)
Parse/5.dcm-8  33.6ms ± 1%  27.9ms ± 0%  -17.00%  (p=0.008 …
```
> Reduce allocations during readNativeFrames, leading to ~15-20% performance improvement

- write.go
- write_test.go
This change cleans up some of the internals of the Native PixelData write code, along with adding more expansive tests for this.
> Add more expansive write native PixelData tests, cleanup internals.

- go.mod
- go.sum
- pkg/tag/tag.go
- read_test.go
This change refactors a test to remove the final testify test dependency (all other tests already adopt the convention to not use an assertion library. More about some thinking on why [here](https://golang.org/doc/faq#testing_framework).
> Update tests allowing removal of stretchr/testify test dependency

- write.go
- write_test.go
I do not think that we should be writing out item VLs as undefined length by default. However, if the caller calls writeVRVL with an item and provides an undefined length VL, then that will be respected.
__Unlike other dicom sequences__, the encapsulated image sequence items cannot be written with undefined length. 
> The encapsulated pixel stream of encoded pixel data is segmented into one or more Fragments, __each of which conveys its own explicit length__. The sequence of Fragments of the encapsulated pixel stream is terminated by a delimiter, thus allowing the support of encoding processes where the resulting length of the entire pixel stream is not known until it is entirely encoded.
http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_8.2.html
The effective change here is that …
> write: Item VL should not default to UndefinedLength

- dataset.go
- dataset_test.go
This addresses the discussion in #183 by introducing a FlatStatefulIterator (that will be GC'd normally, even if it isn't exhausted). This also introduces ExhaustElementChannel which is an easy way for folks using the channel API to ensure it is always exhausted.
At some point either we should deprecate the channel-based API, or we should rename it so that it's not seen as the default for iteration (e.g. name it `FlatChannelIterator` or something). For most usecases, the stateful iterator should be sufficient.
Future improvements can we made to the stateful iterator, for example not recomputing the flat element representation if the dataset hasn't changed from a previous call.
> Introduce FlatStatefulIterator, and ExhaustElementChannel

- dataset.go
- write.go
- write_test.go
Hello. This closes #191.
I've pushed the evaluation of `SkipVRVerification()` into `verifyVROrDefault()` so defaults will be returned even with `SkipVRVerification()` set.
I've also added a guard for VR checking in `writeVRVL()` for `tag.ItemDelimitationItem` like the one for `tag.SequenceDelimitationItem`.
Lastly, I've added two tests to guard against regressions. These tests failed before the changes were made.
> Fixes Write() Failure on SQ Element with SkipVRVerification() set

- read.go
- read_test.go
- write_test.go
Closes #199 via fix laid out in the issue.
I've added a couple tests to confirm correctness of the read/write.
> Set capacity, not length, for bytes buffer allocation

- element.go
- write.go
- write_test.go
Hello!
This PR closes #193 .
This PR changes the behavior of the writer to default to any existing VR value when we do not have any information on the tag, effectively trusting that the caller knows more than we do about this element. I've added a couple tests to verify this is working as intended, and I've also refactored the logic a bit in `verifyVROrDefault` and added some code comments explaining the intent of certain logic paths.
> Bug/Do not replace caller-supplied VRs with UN for unknown Tags

- dataset.go
- pkg/dcmtime/common.go
- pkg/dcmtime/date_test.go
- pkg/dcmtime/datetime_test.go
- pkg/dcmtime/precision.go
- pkg/dcmtime/time_test.go
Just a quick refactor I want to get in to follow up on #171 
Currently, the zero-value of PrecisionLevel is PrecisionYear, and gets more precise as the integer increases.
This creates an environment where the default behavior is not really sane or expected when creating new Date, Time, or Datetime values.
This PR inverts the PrecisionLevel iota, so PrecisionFull is the default zero value.
Currently, when creating a new Date value with just a time, this happens:
```go
package main
import (
"fmt"
"github.com/suyashkumar/dicom/pkg/dcmtime"
"time"
)
func main() {
newDate := dcmtime.Date{
Time: time.Date(2021, 03, 16, 0, 0, 0, 0, time.UTC),
}
fmt.Println("DCM:", newDate.DCM())
// Output:
// DCM: 2021
}
```
Only the year is printed, that's kind of surprising.
This PR changes the behavior to: …
> Refactor/Invert dcmtime.PrecisionLevel values for safe-by-default value creation

- Makefile
- parse.go
- pkg/debug/debug.go
- pkg/debug/default.go
- read.go
This adds in initial build-tag based debug logging instrumentation. If this library is in a binary build with `-tags debug`, the debug statements will be active and log data. Otherwise, the debug logs will be no-ops. 
This stats to address #78.
> Add initial build tag based debug logging

- read.go
- read_test.go
This ensures that we return a recognizable sentinel error when we are trying to parse a file with an unexpected BitsAllocated. 
Previously, we would spin through the readNativeFrames loop without reading forward in the file, leading to an incorrect file offset when parsing the rest of the file which is not desirable.
Longer term, we should aim to possibly support non-standard bitsAllocated (not supported by binary.ByteOrder), though we need to understand what exactly that would mean
> Return a sentinel error for unsupported BitsAllocated

- read.go
- read_test.go
This adds initial support for bitsAllocated=1 assuming LittleEndian ordering. 
I'm not sure if we should be assuming LittleEndian ordering all the time.
> Add initial support for bitsAllocated=1

- pkg/charset/charset.go
Fix #218 
If there are spaces in a particular character set, they are interpreted in the same way as IR6. (Strictly speaking, this accepts data that violates the standard, but it can interpret data that meets the standard.)
> Interpret "" DICOM Character Set as iso-8859-1

- pkg/tag/tag.go
- read.go
- read_test.go
- write.go
- write_test.go
This change ensures that unknown tags with a defined VL are read as bytes (OW). This should fix #231. Previously they would have been read as strings by default.
> Treat Unknown Tags with defined VL as OW

- read.go
- read_test.go
There have been several issues that mention EOF errors. (e.g. #62)  This PR fixes an error that manifested itself with an EOF error, so it may address those.
The problem occurs when there is an odd number of bytes in the pixel data, and even though the value length is even, the parser doesn't count the last padding byte. 
Regarding the implementation, it might be more robust to skip ahead the difference between `vl` and `bytesRead` in `readNativeFrames`, but my understanding of this library and the DICOM standard is that the difference will always be 0 or 1.
> fix issue with odd number of pixel bytes

- cmd/dicomutil/main.go
- dataset.go
- dataset_test.go
- element.go
- parse.go
- pkg/frame/frame.go
- read.go
- read_test.go
Sometimes, the VL of pixel data does not match with calculated value. (I can not provide the sample file to test this)
- In this case, we want to return an error rather than continue to parse and returns an EOF error (very hard to debug why)
- This MR also adds a flag to allow ppl to skip the pixelData and mark it as Encapsulated.
> Fix: pixel data mismatch

- fuzz/dicom_fuzz_test.go
Adds a fuzz test. After some local testing, this fuzz test seems to have found a couple of bugs/performance issues but nothing critical yet :)
> Add Fuzz test

- dataset.go
- parse.go
- pkg/dicomio/reader.go
- read.go
- read_test.go
- write.go
This change wraps the read* methods in read.go into a lightweight reader struct. This allows for easier sharing of some common variables, for example the parse options set without having to inject them through deep read* call chains. 
This also does the following: 
* Moves readMetadata into read.go
*  removes parseOptSet from Dataset.
* updates dicomio.NewReader signature to not include an error (not needed). 
We may want to revisit the naming of some of these entities at some point. There now exists a dicom.reader (unexported) and a lower level dicomio.Reader (referred to as rawReader in this change). Ideally we can also make future refactors to eliminate the need for Parser to be aware of the rawReader (should be easy).
> Refactor read* methods into a lightweight reader struct. 

- element.go
- parse.go
- parse_test.go
- read.go
- read_test.go
This introduces an option to SkipPixelData processing, making use of the new reader struct introduced in #254.
See also, review discussion in #243 that helped motivate the changes I wanted to make in #254.
> Introduce option to SkipPixelData

- dataset.go
- element.go
- parse.go
- parse_test.go
- pkg/tag/tag.go
- read.go
- read_test.go
- write.go
- write_test.go
This addresses _some_ of the discussion in #224. The SkipProcessingPixelDataValue option causes the PixelData bytes to be read into the element, but not processed any further. This option provides an option to save the CPU cycles processing NativePixel data but still gives a roundtrip-able Dataset.
If you want to save both CPU and Memory, you can instead use the SkipPixelData option, which doesn't load the PixelData bytes into memory at all.
In the future, we should consider an option to lazy load/process all Element values if possible.
> Add option to skip Element Value processing of PixelData, while preserving roundtrip read/write

- .github/workflows/bench_pr.yml
- .github/workflows/bench_push.yml
- Makefile
- parse_test.go
This change updates the Parse benchmark to operate across useful ParseOptions, adds memory benchmarking, and updates some benchmark params. 
For example, we can take a look at the CPU / memory differences across the new ParseOptions for one of the test dicoms:
```
BenchmarkParse/NoOptions/4.dcm-4                                     	      10	 106876945 ns/op	120572543 B/op	    2160 allocs/op
BenchmarkParse/SkipPixelData/4.dcm-4                                 	      10	    531193 ns/op	   34900 B/op	    2144 allocs/op
BenchmarkParse/SkipProcessingPixelDataValue/4.dcm-4                  	      10	   1807256 ns/op	 7573518 B/op	    2146 allocs/op
```
> Benchmark across Parse options, add memory benchmarking.

- parse.go
- parse_internal_test.go
- parse_test.go
- pkg/dicomio/reader.go
- read.go
The -new- PR for this from another branch.
This fix allows reading until EOF, without providing "bytesToRead", it keeps the previous Parse signature for backwards compatibility and creates a new ParseUntilEOF function which doesn't require the extra param.
> allow for reading until EOF with the function ParseUntilEOF 

- write.go
fix #275 
Values with VRs constructed of character strings, except in the case of the VR UI, shall be padded with SPACE characters (20H, in the Default Character Repertoire) when necessary to achieve even length. 
AE is no exception.
TYVM @suyashkumar :)
> fix Application Entity (AE) value parsing

- cmd/dicomutil/main.go
Where appropriate, this calls log.Infof along with a return instead of log.Fatalf to ensure defered functions are actually run in those exit scenarios. 
Looking at dicomutil, it could probably use some improvements and a refactor as well in general as an example program.
> Log and return to ensure defers are still called in example dicomutil.

- cmd/dicomutil/main.go
- dataset.go
- element.go
- element_test.go
- parse_internal_test.go
- pkg/frame/encapsulated.go
- pkg/frame/frame.go
- pkg/frame/native.go
- read.go
- read_test.go
- write_test.go
This change introduces well-defined equality methods for `Dataset`, `Element`, and some other data structures. This greatly speeds up tests that rely on checking equality of datasets (that previously needed reflection). For example, it reduces the total test suite from `1m24s` to `10s` on GitHub actions (mostly due to one test). These methods may also be of use to library users.
However, this does mean that if new fields are added to any of these structs it is important for the `Equals` method to be updated as well. For now this will be enforced during code review (helped by the fact most of these structs should not fail often), but we should investigate lint rules or some auto-generated reflection based tests that can help catch when this doesn't happen (see #281).  
This change also …
> Add Dataset & Element equality methods, greatly speeding up tests that rely on dataset comparisons.

- write.go
- write_test.go
When reading the code base, I found there are 2 mismatch between read and write process:
- If the data length is even, we must append 1 byte to round it up
- If the transfersynax is BigEndian, we must apply the byte order when writing the pixeldata.
> write: fix/support BigEndian PixelData writes, pad odd byte lengths with extra byte

- parse.go
- pkg/dicomio/reader.go
- pkg/dicomio/writer.go
- read.go
- read_test.go
- write.go
Making this refactor, along with other API-breaking changes being made in the next release. If users need an interface, they can create one client-side as needed for their use cases! This also matches the Writer to use a pointer struct for consistency.
This closes #319.
> Remove Reader interface in favor of using the struct directly, use writer struct pointer for consistency

- dataset_test.go
- element_test.go
- parse.go
- parse_test.go
- pkg/charset/charset.go
- pkg/tag/tag.go
- read.go
- read_test.go
- write.go
- write_test.go
This PR is adapted from the [previous one](https://github.com/suyashkumar/dicom/pull/234).
The main new addition it makes to this existing `s/read-un-as-sq` branch is treating unknown elements* as bytes not strings. It also contains changes from a main branch rebase.
*outside of the implicit syntax+undefined length case
> Handle unknowns completely

- dataset_test.go
- parse_test.go
- pkg/tag/tag.go
- read.go
- write.go
- write_test.go
This addresses #220 (and one of the dicoms in #327) by treating elements with a VR=UN and undefined VL as Sequences.
This pulls from work that I and @jabillings did previously (#235).
Some follow on changes may be needed to support this part of [the spec CP](https://dicom.nema.org/dicom/cp/cp246_01.pdf):
> If at some point an application knows the actual VR for an Attribute of VR UN (e.g. has its own applicable data dictionary), it can assume that the Value Field of the Attribute is encoded in Little Endian byte ordering with implicit VR encoding, irrespective of the current TransferSyntax.
> Read elements with VR=UN and undefined VL as SQ

- read_test.go
- write.go
- write_test.go
This fixes #328. This change will also help set the stage for roundtrip tests for transfer syntax uid inference in the case of missing transfer syntax UIDs (part of #327). 
This also makes an API breaking change to return an error from NewWriter, which imo makes sense.
For the future:
- should we give this option as something to _always_ override whatever transfer syntax is present (or if not present, use the override as well)?
> Add WriteOption to override missing transfer syntax in dataset

- parse.go
- parse_internal_test.go
- parse_test.go
- write.go
This PR attempts to infer missing transfer syntax in dicoms during Parse.
Specifically: 
* When transfer syntax is missing in dicom metadata, attempt to infer the correct transfer syntax by peeking the next 100bytes and trying to read an element without an error. This isn't foolproof, but one option to start with.
* This also makes test updates to support testfiles/ that may not have PixelData.
* This also introduces a write option to write dicoms without transfer syntax elements, in order to write some "roundtrip" unit tests for this behavior on Parse.
I was able to successfully test using some test data from #327, but I need to do some more investigation to see if we can safely add those to our test files (licensing and otherwise).
Things to consider in the future:
* Try deflated little …
> Parse: If transfer syntax is missing, attempt to infer it by peeking next 100 bytes.

- parse.go
- parse_test.go
- pkg/charset/charset.go
- pkg/dicomio/reader.go
This change implements an option to allow an unknown specific character set when parsing a DICOM and fallback to using UTF-8.
For context, in my application of this parser, we are seeing erroneous specific character sets such as
```
ISO IR 192
ISO_2022_IR_6
NONE
```
Current behaviour is that parsing fails immediately upon encountering an unknown character set, and the error also indicates that it will fallback to utf-8 (which is misleading since it just errors out instead of actually falling back). It seems there was a `TODO` in place for this, so this change implements the option to allow this.
> Allow unknown specific character set to default to UTF-8 encoding when parsing

- dataset_test.go
- pkg/personname/examples_test.go
In Go 1.24, `go vet` enforces correct naming on examples. This ensures our testable example names are proper. https://go.dev/doc/go1.24#vet
> Rename testable examples to follow Go convention

- read.go
- read_test.go
This addresses #349.
OB and OW fields with undefined length now parse their contents as a sequence, concatenating all the bytes in the items within.
`readBytes` and `readString` return an error if the VL is `tag.VLUndefinedLength`, as parsing these tags shouldn't fall to these, and we avoid future accidental 4GB allocations.
Trying to parse the (contrived) file from the issue now returns:
```
readElement: error when reading value for element (0049,1001): unable to read field of undefined length
```
Parsing a real DICOM file with an OB field of undefined length parses without error.
I made this a constant (`ErrorExpectedDefinedLength`) so it could be used in a test, but I think it may be worth returning a custom error so we include the VR as well, e.g. 
```
readElement: error when reading …
```
> Parse undefined length OB/OW elements
